
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.tinyscript]
audit-as-crates-io = true

[policy.tinyscript-derive]
audit-as-crates-io = true

[[exemptions.anstyle]]
version = "1.0.11"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.45"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.44"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-run"

[[exemptions.glob]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.11.0"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.3.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.101"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.2"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.10"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.rstest]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.rstest_macros]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.106"
criteria = "safe-to-deploy"

[[exemptions.tinyscript]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.tinyscript-derive]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.11"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.27"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.7.13"
criteria = "safe-to-run"
